---
# Download composer from getcomposer.org
- get_url: url=https://getcomposer.org/installer dest=~/install-composer.php
  tags:
    - composer

- name: "Install php5-cli"
  apt: name=php5-cli state=installed
  sudo: yes
  sudo_user: root

# Install composer
- command: php install-composer.php chdir=~
  tags:
    - composer

# Make sure there is a ~/bin folder
- file: path=~/bin state=directory
  tags:
    - composer

# Move composer.phar to ~/bin
- command: mv ~/composer.phar ~/bin/composer
  tags:
    - composer
