---
# Download composer from getcomposer.org
- get_url: url=https://getcomposer.org/installer dest=~/install-composer.php
  tags:
    - composer

# Install composer
- command: php install-composer.php
  tags:
    - composer

# Make sure there is a ~/bin folder
- file: path=~/bin state=directory
  tags:
    - composer

# Move composer.phar to ~/bin
- command: mv ~/composer.phar ~/bin/composer
  tags:
    - composer
